version: 2

# Set the version of Python and other tools you might need
build:
   os: ubuntu-22.04
   tools:
     python: "3.10"

sphinx:
   configuration: docs/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
# formats:
#    - pdf

python:
   install:
   - requirements: docs/requirements.txt
   - method: pip
     path: .